version: '3.8'

services:
  # Backend service (Flask API)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"  # Porta da API Flask
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
      - redis
    networks:
      - monitoramento-net

  # Redis service (mensageria)
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoramento-net

  # Database service (SQLite3)
  db:
    image: nouchka/sqlite3:latest
    container_name: sqlite3
    volumes:
      - ./backend/db:/data
    networks:
      - monitoramento-net

  # Telegram Bot service (Telebot)
  telegram-bot:
    build:
      context: ./bot-telegram
      dockerfile: Dockerfile
    container_name: telegram-bot
    volumes:
      - ./bot-telegram:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    networks:
      - monitoramento-net

  # Frontend service (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"  # Porta do frontend React
    networks:
      - monitoramento-net

networks:
  monitoramento-net:
    driver: bridge
